### ISSUE TITLE
Version incompatibility with later versions of Faraday

### ISSUE THREAD

**Issue by DriftingShadows** [omniauth/omniauth-oauth2#121]
Are there any plans on updating the gem dependency requirement on the oauth2 gem? The current specified gem for oauth2 doesn't support faraday versions from v0.10. Otherwise I guess I'll just downgrade the faraday gem.

**Comment by mikemarsian** [comment]
Any update on that?

**Comment by BobbyMcWho** [comment]
Closing because I believe this has been handled in #124
