### ISSUE TITLE
state parameter change to hashing code. 

### ISSUE THREAD

**Issue by Drblack101** [omniauth/omniauth-oauth2#150]
I'm using the Microsoft identity platform and OAuth 2.0 authorization code flow to authorize user information from Microsoft Azure.

In my Ruby code I parse the state parameter to Microsoft:
`config.omniauth :azure_oauth2, client_id: "xxxxxxxxxxxx", client_secret: "xxxxxxxxxxxx", tenant_id: "xxxxxxxxxxxx", scope: "user.read", state: "development", response_type: "token", response_mode: "query"`

I'm supposed to receive a state parameter with the same value ("development") as I sent. But seems I got a hashing value for it after Microsoft received my request:

`https://login.microsoftonline.com/xxxxxxxx&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fomniauth%2Fazure_oauth2%2Fcallback&response_type=code&scope=user.read&state=6ff45c77bf433d3bf33dd8df956fda77d62467c0b29b6f4c&sso_reload=true`

**Comment by BobbyMcWho** [comment]
[state](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1) isn't something that you hard code, it is generated [by the strategy](https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L63), and stored in [session state](https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L75). The state returned by the provider is validated in the [callback phase](https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L86) against the value in the session state.
