### ISSUE TITLE
CSRF Detected - When changing Subdomain to 'app' instead of 'www'

### ISSUE THREAD

**Issue by chabdulbasit17** [omniauth/omniauth-oauth2#164]
Hi, I have a multi-tenant app and I'm using sign in with Google using omniauth. The functionality was fine when I was using subdomain 'www' in the redirect_uri, but now due to an internal change, we have to change the public subdomains of our site to 'app' which means the redirect_uri now would be like, say ```app.lvh.me```  instead of ```www.lvh.me```
Since the change, the ```session['omniauth.state'] ``` that is set in the request phase, is now null in the callback phase at the comparison on the following line: 
``` (request.params["state"].to_s.empty? || request.params["state"] != session.delete("omniauth.state")) ```

Please advise on this if this is an issue on the omniauth side

**Comment by BobbyMcWho** [comment]
Make sure you update the allowed redirect Uris in your Google developer configuration, and update the omniauth redirect uri setting. 

I believe this is a configuration issue on your end not OmniAuth
