### ISSUE TITLE
Callback URI

### ISSUE THREAD

**Issue by reiz** [omniauth/omniauth-oauth2#180]
Where can I define my callback URI?

**Comment by BobbyMcWho** [comment]
Please refer to the gem that you're using that consumes this gem's documentation, such as: https://github.com/omniauth/omniauth_openid_connect

**Comment by reiz** [comment]
@BobbyMcWho Thanks for the fast reply!! 
 
I'm refer to the [Microsoft Graph Sample App](https://github.com/microsoftgraph/msgraph-sample-rubyrailsapp). I was not sure how the callback is assembled because there is not place there I can explicitly set it. Is my assumption correct that omniauth assembles the callback uri by this pattern: 

```
<HOST>/auth/<CALLBACK_STRATEGY_NAME>/callback
```

**Comment by BobbyMcWho** [comment]
You may want to use a gem like https://github.com/synth/omniauth-microsoft_graph 

I'd ask there, as this gem is the backbone for other strategies which may configure things differently depending on the provider
