### ISSUE TITLE
Expose ability to refresh access token

### ISSUE THREAD

**Issue by myitcv** [omniauth/omniauth-oauth2#40]
I am using omniauth-oauth2 with the [Google strategy](https://github.com/zquestz/omniauth-google-oauth2)

My use case is roughly as follows:
- I have an initialiser with client id and secret etc, requesting offline access - entirely standard
- I store the returned `access_token`, `refresh_token` along with the `uid` etc in a `user` model
- Whenever I request data on behalf of said user, I pull the `access_token` from the corresponding attribute on the `user` model
- But this access token can (and does) expire. At a later stage (possibly when the user themselves is offline) I need to refresh their access token because it has expired

As far as I can tell, there is no omniauth\* provided means of achieving a refresh.

What's the best way of achieving this? Is there something within omniauth that can be exposed to make this easier? Something along the lines of [this](https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L76)

At the moment I have a rather unattractive helper method that utilises the same ENV variables to extract the client id, secret etc, takes a user object and performs a refresh using an approach not dissimilar to [this](https://github.com/zquestz/omniauth-google-oauth2/issues/37)

Any thoughts?

**Comment by deeTEEcee** [comment]
while randomly searching how to do setup google calendar connections, i found this code in someone else's repository. there seems to be many ways but this one seemed fairly understandable...
```
# client being some model i created that stores the info. 
  def refresh_current_token(client)
    oauth_client = OAuth2::Client.new(
      Rails.application.secrets.omniauth['google_calendar']['client_id'], Rails.application.secrets.omniauth['google_calendar']['secret'],
      :site => "https://accounts.google.com",
      :token_url => "/o/oauth2/token",
      :authorize_url => "/o/oauth2/auth")
    access_token = OAuth2::AccessToken.from_hash(oauth_client, {:refresh_token => client.refresh_token})
    access_token = access_token.refresh!
    client.access_token = access_token.token
    client.expires_at = Time.now + access_token.expires_in
    client.save
  end
```

**Comment by technic-tec** [comment]
Got this page through search, a bit confused. Link an answer here about the odd oauth2 playground issue for later reference: http://stackoverflow.com/questions/33771197/fail-to-refresh-access-token-in-oauth-2-0-playground

**Comment by thbar** [comment]
Sharing what I learned, and building up on @deeTEEcee answer (and others): if you have an existing strategy (like `Freckle` below which I'm building at the moment), you can leverage a bit more the strategy to build the client like this:

```ruby
    strategy = OmniAuth::Strategies::Freckle.new(nil, key, secret)
    client = strategy.client

    oauth2_token = data_integration.oauth2_token
    oauth2_refresh_token = data_integration.oauth2_refresh_token
    
    token = OAuth2::AccessToken.new client, oauth2_token, {refresh_token: oauth2_refresh_token}
    new_token = token.refresh!

    data_integration.oauth2_token = new_token.token unless new_token.token.blank?
    data_integration.oauth2_refresh_token = new_token.refresh_token unless new_token.refresh_token.blank?
    data_integration.oauth2_token_expires_at = Time.at(new_token.expires_at) unless new_token.expires_at.blank?
    data_integration.save!
```

Hope this helps!

**Comment by polysaturate** [comment]
Quick example on how to work with dynamic strategies:

```ruby
provider = :bitbucket
strategy = OmniAuth::Strategies.const_get(provider.to_s.capitalize).new(
      nil,
      Figaro.env.send("#{provider.to_s}_key"),
      Figaro.env.send("#{provider.to_s}_secret")
    )
```

**Comment by tayloredwebsites** [comment]
I found this article helpful for refreshing access tokens from google:
https://stackoverflow.com/questions/12792326/how-do-i-refresh-my-google-oauth2-access-token-using-my-refresh-token#14491560
