### ISSUE TITLE
Design issue - GET => POST

### ISSUE THREAD

**Issue by homakov** [omniauth/omniauth-oauth2#52]
Related http://homakov.blogspot.com/2014/01/two-severe-wontfix-vulnerabilities-in.html

When we load GET /connect/facebook it starts auth flow automatically. It's login fixation by-default. Since it's a state changing request we should use either POST /connect/fb with appropriate csrf_token or, more likely, /connect/fb?authenticity_token=CURRENT_TOKEN.

This is not much of a breaking change, but will protect from account hijacking for those websites connecting Providers to master account as login options.

**Comment by homakov** [comment]
bump

**Comment by tmilewski** [comment]
This is present in the Omniauth gem. Thanks!
